version: 2
jobs:
  build:
    branches:
      only:
        - master
        - /v[0-9\.]+/
        - /rc-.*/
    docker:
      - image: naquid/meta-builder
    steps:
      - run: git clone https://github.com/umegaya/naquid
      - run: cd naquid && git submodule sync && git submodule update --init
      - run: cd naquid/tools/certs && bash ./generate-certs.sh
      - run: echo "127.0.0.1 test.qrpc.io" >> /etc/hosts
      - run: cd naquid && make test TEST_OS=linux